# On any commit, builds pylode to act as a test
# On master, build a minified release, push to ECR and deploy to EKS cluster

image:
  name: python:3.7.4-alpine3.10

options:
  docker: true

pipelines:
  branches:
    master:
      - step:
          name: Build and push image to ECR
          caches:
            - docker
          script:
            # build the image
            - docker build -t ldr/ogc-api . -f Dockerfile
            # push image to AWS ECR
            - pipe: atlassian/aws-ecr-push-image:1.3.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                ROLE_ARN: $ROLE_ARN
                IMAGE_NAME: ldr/ogc-api
      - step:
          name: Deploy to Kubernetes
          script:
            # replace image name in deployment.yml
            # - sed -i -e "s/IMAGE_NAME/$ECR_URI\/ldr\/globe:latest/g" deploy/kubernetes/deployment.yml
            # run kubectl apply
            # if image name didn't change, kubectl apply won't do anything
            # might need image versioning
            - pipe: atlassian/aws-eks-kubectl-run:1.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                ROLE_ARN: $ROLE_ARN
                CLUSTER_NAME: "ldr-eks-cluster"
                KUBECTL_COMMAND: "apply"
                RESOURCE_PATH: "deployment.yaml"
      - step:
          name: Rollout restart
          script:
            # if image name didn't change, use rollout
            # rollout restart will "re-rollout" the deployment so the pods get the new image
            - pipe: atlassian/aws-eks-kubectl-run:1.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                ROLE_ARN: $ROLE_ARN
                CLUSTER_NAME: "ldr-eks-cluster"
                KUBECTL_COMMAND: "rollout restart deployment ldr-ogc-api-deployment"
