apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldr-ogc-api-deployment
  labels:
    app: ldr-ogc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldr-ogc-api
  template:
    metadata:
      labels:
        app: ldr-ogc-api
    spec:
      containers:
      - name: ogc-api
        image: 680471986828.dkr.ecr.ap-southeast-2.amazonaws.com/ldr/ogc-api:latest
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: "2Gi"
              cpu: "1000m"
          limits:
            memory: "4Gi"
#            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: ldr-ogc-api-service
spec:
  selector:
    app: ldr-ogc-api
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000