apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldr-ogc-api-deployment
  labels:
    app: ldr-ogc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldr-ogc-api
  template:
    metadata:
      labels:
        app: ldr-ogc-api
    spec:
      containers:
      - name: ogc-api
        image: 680471986828.dkr.ecr.ap-southeast-2.amazonaws.com/ldr/ogc-api:latest
        ports:
        - containerPort: 9000
        env:
          - name: SPARQL_ENDPOINT
            value: "http://fuseki.surroundaustralia.com/asgs_dggs/query"
          - name: LANDING_PAGE_URL
            value: "http://a25a8a2eda9464b7fb3931bf12de441b-1975690911.ap-southeast-2.elb.amazonaws.com"
          - name: DATASET_URI
            value: "https://w3id.org/dggs/asgs2016"
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "100m"
          limits:
            memory: "2Gi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: ldr-ogc-api-service
spec:
  selector:
    app: ldr-ogc-api
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000